name: Get related PR object

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      id: get-pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.rest.pulls.get(request)
            console.log(result.data)
            core.exportVariable('RELATED_REF', results.data.head.ref)
            core.exportVariable('RELATED_SHA', results.data.head.ref)
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
