name: Get related PR object

outputs:
  ref:
    description: The name of the current PR
    value: ${{ steps.get-pr.outputs.ref }}
  sha:
    description: The current commit
    value: ${{ steps.get-pr.outputs.sha }}
  
runs:
  using: composite

  steps:
    - uses: actions/github-script@v6
      id: get-pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.rest.pulls.get(request)
            core.setOutput('ref', result.data.head.ref)
            core.setOutput('sha', result.data.head.sha)
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
