name: Testing Comment hook

on:
  issue_comment:
    types: [ created ]

defaults:
  run:
    shell: bash
jobs:
  pr:
    name: Retrieve current PR context
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/get-pr
      - run: echo $RELATED_REF
      - run: echo $RELATED_SHA
