name: Testing Comment hook

on:
  issue_comment:
    types: [ created ]

defaults:
  run:
    shell: bash
jobs:
  pr:
    name: Retrieve current PR context
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    outputs:
      ref: ${{ steps.get-pr.outputs.ref }}
      sha: ${{ steps.get-pr.outputs.sha }}

    steps:
      - uses: actions/checkout@v3
      - id: get-pr
        uses: ./.github/actions/get-pr
      - run: echo "${{ steps.pr.outputs.ref }}:${{ steps.pr.outputs.sha }}"
  
  validate:
    name: Check results from another job
    runs-on: ubuntu-latest
    needs: pr
      steps:
        - run: echo "${{ needs.pr.outputs.ref }}:${{ needs.pr.outputs.sha }}"
    