name: Testing Comment hook

on:
  issue_comment:
    types: [ created ]

defaults:
  run:
    shell: bash
jobs:
  pr:
    name: Retrieve current PR context
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: actions/checkout@v3
      - id: get-pr
        uses: ./.github/actions/get-pr

  validate:
    name: Validate PR results
    runs-on: ubuntu-latest
    needs: pr
    steps:
      - run: echo "Ref is $RELATED_REF"
      - run: echo "SHA is $RELATED_SHA"